# Generated by Django 2.1.3 on 2019-05-27 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20190527_0753'),
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='forum',
            name='posts',
            field=models.ManyToManyField(blank=True, related_name='_forum_posts_+', to='main.Post'),
        ),
    ]
