# Generated by Django 2.1.3 on 2019-07-01 19:39

from django.db import migrations, models
import forum.models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_forum_posts'),
    ]

    operations = [
        migrations.AddField(
            model_name='forum',
            name='file',
            field=models.FileField(default=1, max_length=300, upload_to=forum.models.upload_path_file),
            preserve_default=False,
        ),
    ]
