# Generated by Django 2.1.3 on 2019-07-02 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_forum_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forum',
            name='join_code',
            field=models.CharField(blank=True, max_length=8),
        ),
    ]
