# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2018-08-05 22:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import push_page.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to=push_page.models.upload_path)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True)),
                ('pub_date', models.DateTimeField(verbose_name='Post date')),
            ],
        ),
        migrations.CreateModel(
            name='PushPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(max_length=50)),
                ('template', models.CharField(max_length=150)),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='push_page.PushPage'),
        ),
        migrations.AddField(
            model_name='picture',
            name='content',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='push_page.Post'),
        ),
    ]
