# Generated by Django 2.1.3 on 2018-11-04 19:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import main.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('course_code', models.CharField(blank=True, max_length=20, null=True)),
                ('module_code', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('field', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Download',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False)),
                ('start', models.DateTimeField(verbose_name='Started On')),
                ('finish', models.DateTimeField(blank=True, null=True, verbose_name='Finished On')),
            ],
        ),
        migrations.CreateModel(
            name='Educational_Institution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('ownership_type', models.CharField(choices=[('pvt', 'Private'), ('pbc', 'Public'), ('gvt', 'Government')], max_length=50)),
                ('institution_type', models.CharField(choices=[('clg', 'College'), ('uni', 'University')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(max_length=300, upload_to=main.models.upload_path_file)),
                ('name', models.CharField(max_length=20)),
                ('extension', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(max_length=300, upload_to=main.models.upload_path_image)),
            ],
        ),
        migrations.CreateModel(
            name='Instructor_Teaches',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Course')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('post_type', models.IntegerField()),
                ('pub_date', models.DateTimeField(verbose_name='Date Published')),
                ('files', models.ManyToManyField(blank=True, to='main.File')),
                ('images', models.ManyToManyField(blank=True, to='main.Image')),
            ],
        ),
        migrations.CreateModel(
            name='Post_To_Chat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Post')),
                ('post_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Department')),
            ],
        ),
        migrations.CreateModel(
            name='Post_To_Class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Post')),
                ('post_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Instructor_Teaches')),
            ],
        ),
        migrations.CreateModel(
            name='Post_To_Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Post')),
            ],
        ),
        migrations.CreateModel(
            name='Post_To_Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Post')),
            ],
        ),
        migrations.CreateModel(
            name='Post_To_Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Post')),
            ],
        ),
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reminder_for', models.IntegerField()),
                ('title', models.CharField(max_length=20)),
                ('note', models.TextField(blank=True)),
                ('due_date', models.DateTimeField()),
                ('due_time', models.DateTimeField()),
                ('place', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Reminder_To_Class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reminder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Reminder')),
                ('reminder_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Instructor_Teaches')),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('section_id', models.CharField(max_length=2)),
                ('department_in', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Department')),
                ('section_takes', models.ManyToManyField(to='main.Course')),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('Mr.', 'Mr.'), ('Ms.', 'Ms.'), ('Mrs.', 'Mrs.'), ('Dr.', 'Doctor'), ('Prof.', 'Professor')], max_length=15)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('role', models.CharField(choices=[('Dean', 'Dean'), ('Associate Dean', 'Associate Dean'), ('Registrar', 'Registrar'), ('Department Head', 'Department Head'), ('Program Coordinator', 'Program Coordinator'), ('Instructor', 'Instructor'), ('Lab Technician', 'Lab Technician')], max_length=15)),
                ('department_in', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Department')),
                ('university_in', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Educational_Institution')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('section', models.CharField(max_length=5)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('reg_id', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('chat_id', models.IntegerField(default=0)),
                ('class_in', models.ManyToManyField(to='main.Instructor_Teaches')),
                ('department_in', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Department')),
                ('university_in', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Educational_Institution')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tracking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField()),
                ('del_on', models.DateTimeField(verbose_name='Delivery On')),
                ('read_on', models.DateTimeField(blank=True, null=True, verbose_name='Read On')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Post')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Student')),
            ],
        ),
        migrations.AddField(
            model_name='post_to_student',
            name='post_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Student'),
        ),
        migrations.AddField(
            model_name='post_to_staff',
            name='post_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Staff'),
        ),
        migrations.AddField(
            model_name='post_to_section',
            name='post_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Section'),
        ),
        migrations.AddField(
            model_name='post',
            name='post_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Staff'),
        ),
        migrations.AddField(
            model_name='instructor_teaches',
            name='instructor',
            field=models.ManyToManyField(to='main.Staff'),
        ),
        migrations.AddField(
            model_name='instructor_teaches',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Section'),
        ),
        migrations.AddField(
            model_name='image',
            name='post_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Staff'),
        ),
        migrations.AddField(
            model_name='file',
            name='post_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Staff'),
        ),
        migrations.AddField(
            model_name='download',
            name='file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.File'),
        ),
        migrations.AddField(
            model_name='download',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Student'),
        ),
        migrations.AddField(
            model_name='department',
            name='university_in',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Educational_Institution'),
        ),
        migrations.AddField(
            model_name='course',
            name='given_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Department'),
        ),
    ]
