# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2018-09-18 21:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student_takes',
            name='class_in',
        ),
        migrations.RemoveField(
            model_name='student_takes',
            name='student',
        ),
        migrations.AddField(
            model_name='student',
            name='class_in',
            field=models.ManyToManyField(to='main.Instructor_Teaches'),
        ),
        migrations.DeleteModel(
            name='Student_Takes',
        ),
    ]
