# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-10-15 18:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcement',
            name='count',
        ),
        migrations.RemoveField(
            model_name='course',
            name='code',
        ),
        migrations.RemoveField(
            model_name='department',
            name='university',
        ),
        migrations.RemoveField(
            model_name='material',
            name='count',
        ),
        migrations.AlterField(
            model_name='lecturer',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
