# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2018-09-19 23:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20180918_2157'),
    ]

    operations = [
        migrations.AddField(
            model_name='reminder',
            name='note',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='files',
            field=models.ManyToManyField(blank=True, default=None, null=True, to='main.File'),
        ),
        migrations.AlterField(
            model_name='post',
            name='images',
            field=models.ManyToManyField(blank=True, default=None, null=True, to='main.Image'),
        ),
    ]
