# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-11-16 00:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_lecturer_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecturer',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
