# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2018-03-03 12:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20180303_1155'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Teacher'),
        ),
        migrations.AlterField(
            model_name='material',
            name='file',
            field=models.FileField(max_length=300, upload_to=main.models.upload_path),
        ),
    ]
