# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2018-09-20 19:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20180919_2315'),
    ]

    operations = [
        migrations.CreateModel(
            name='Download',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False)),
                ('start', models.DateTimeField(verbose_name='Started On')),
                ('finish', models.DateTimeField(blank=True, null=True, verbose_name='Finished On')),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.File')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Student')),
            ],
        ),
        migrations.AlterField(
            model_name='staff',
            name='role',
            field=models.CharField(choices=[('Dean', 'Dean'), ('Associate Dean', 'Associate Dean'), ('Registrar', 'Registrar'), ('Department Head', 'Department Head'), ('Program Coordinator', 'Program Coordinator'), ('Instructor', 'Instructor'), ('Lab Technician', 'Lab Technician')], max_length=15),
        ),
        migrations.AlterField(
            model_name='tracking',
            name='read_on',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Read On'),
        ),
    ]
