# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2018-03-03 17:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20180303_1257'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement_to',
            name='pub_date',
            field=models.DateTimeField(null=True, verbose_name='Date Published'),
        ),
        migrations.AddField(
            model_name='material_to',
            name='pub_date',
            field=models.DateTimeField(null=True, verbose_name='Date Published'),
        ),
    ]
