# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2018-10-05 19:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20180920_1905'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='section',
            field=models.CharField(default=1, max_length=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='chat_id',
            field=models.IntegerField(blank=True),
        ),
    ]
