# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-10-25 19:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20171025_1852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecturer',
            name='last_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='lecturer',
            name='lect_id',
            field=models.CharField(max_length=20),
        ),
    ]
